/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.price.list.model.impl;

import com.liferay.commerce.price.list.model.CommercePriceListContractRel;
import com.liferay.commerce.price.list.model.CommercePriceListContractRelModel;
import com.liferay.commerce.price.list.model.CommercePriceListContractRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommercePriceListContractRel service. Represents a row in the &quot;CommercePriceListContractRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CommercePriceListContractRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercePriceListContractRelImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommercePriceListContractRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommercePriceListContractRelModelImpl
	extends BaseModelImpl<CommercePriceListContractRel>
	implements CommercePriceListContractRelModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce price list contract rel model instance should use the <code>CommercePriceListContractRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommercePriceListContractRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR},
		{"commercePriceListContractRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"commerceContractId", Types.BIGINT},
		{"commercePriceListId", Types.BIGINT}, {"order_", Types.INTEGER},
		{"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commercePriceListContractRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceContractId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercePriceListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommercePriceListContractRel (uuid_ VARCHAR(75) null,commercePriceListContractRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceContractId LONG,commercePriceListId LONG,order_ INTEGER,lastPublishDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommercePriceListContractRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commercePriceListContractRel.order ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommercePriceListContractRel.order_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListContractRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListContractRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.price.list.model.CommercePriceListContractRel"),
		true);

	public static final long COMMERCECONTRACTID_COLUMN_BITMASK = 1L;

	public static final long COMMERCEPRICELISTID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ORDER_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommercePriceListContractRel toModel(
		CommercePriceListContractRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CommercePriceListContractRel model =
			new CommercePriceListContractRelImpl();

		model.setUuid(soapModel.getUuid());
		model.setCommercePriceListContractRelId(
			soapModel.getCommercePriceListContractRelId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCommerceContractId(soapModel.getCommerceContractId());
		model.setCommercePriceListId(soapModel.getCommercePriceListId());
		model.setOrder(soapModel.getOrder());
		model.setLastPublishDate(soapModel.getLastPublishDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommercePriceListContractRel> toModels(
		CommercePriceListContractRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommercePriceListContractRel> models =
			new ArrayList<CommercePriceListContractRel>(soapModels.length);

		for (CommercePriceListContractRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.price.list.model.CommercePriceListContractRel"));

	public CommercePriceListContractRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commercePriceListContractRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommercePriceListContractRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commercePriceListContractRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommercePriceListContractRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommercePriceListContractRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommercePriceListContractRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommercePriceListContractRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListContractRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommercePriceListContractRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommercePriceListContractRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommercePriceListContractRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommercePriceListContractRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommercePriceListContractRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommercePriceListContractRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommercePriceListContractRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommercePriceListContractRel.class.getClassLoader(),
			CommercePriceListContractRel.class, ModelWrapper.class);

		try {
			Constructor<CommercePriceListContractRel> constructor =
				(Constructor<CommercePriceListContractRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map
		<String, Function<CommercePriceListContractRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommercePriceListContractRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommercePriceListContractRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommercePriceListContractRel, Object>>();
		Map<String, BiConsumer<CommercePriceListContractRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommercePriceListContractRel, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object uuidObject) {

					commercePriceListContractRel.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListContractRelId",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.
						getCommercePriceListContractRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListContractRelId",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object commercePriceListContractRelIdObject) {

					commercePriceListContractRel.
						setCommercePriceListContractRelId(
							(Long)commercePriceListContractRelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object companyIdObject) {

					commercePriceListContractRel.setCompanyId(
						(Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object userIdObject) {

					commercePriceListContractRel.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object userNameObject) {

					commercePriceListContractRel.setUserName(
						(String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object createDateObject) {

					commercePriceListContractRel.setCreateDate(
						(Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object modifiedDateObject) {

					commercePriceListContractRel.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"commerceContractId",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getCommerceContractId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceContractId",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object commerceContractIdObject) {

					commercePriceListContractRel.setCommerceContractId(
						(Long)commerceContractIdObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListId",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.
						getCommercePriceListId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListId",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object commercePriceListIdObject) {

					commercePriceListContractRel.setCommercePriceListId(
						(Long)commercePriceListIdObject);
				}

			});
		attributeGetterFunctions.put(
			"order",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getOrder();
				}

			});
		attributeSetterBiConsumers.put(
			"order",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object orderObject) {

					commercePriceListContractRel.setOrder((Integer)orderObject);
				}

			});
		attributeGetterFunctions.put(
			"lastPublishDate",
			new Function<CommercePriceListContractRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListContractRel commercePriceListContractRel) {

					return commercePriceListContractRel.getLastPublishDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			new BiConsumer<CommercePriceListContractRel, Object>() {

				@Override
				public void accept(
					CommercePriceListContractRel commercePriceListContractRel,
					Object lastPublishDateObject) {

					commercePriceListContractRel.setLastPublishDate(
						(Date)lastPublishDateObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCommercePriceListContractRelId() {
		return _commercePriceListContractRelId;
	}

	@Override
	public void setCommercePriceListContractRelId(
		long commercePriceListContractRelId) {

		_commercePriceListContractRelId = commercePriceListContractRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommerceContractId() {
		return _commerceContractId;
	}

	@Override
	public void setCommerceContractId(long commerceContractId) {
		_columnBitmask |= COMMERCECONTRACTID_COLUMN_BITMASK;

		if (!_setOriginalCommerceContractId) {
			_setOriginalCommerceContractId = true;

			_originalCommerceContractId = _commerceContractId;
		}

		_commerceContractId = commerceContractId;
	}

	public long getOriginalCommerceContractId() {
		return _originalCommerceContractId;
	}

	@JSON
	@Override
	public long getCommercePriceListId() {
		return _commercePriceListId;
	}

	@Override
	public void setCommercePriceListId(long commercePriceListId) {
		_columnBitmask |= COMMERCEPRICELISTID_COLUMN_BITMASK;

		if (!_setOriginalCommercePriceListId) {
			_setOriginalCommercePriceListId = true;

			_originalCommercePriceListId = _commercePriceListId;
		}

		_commercePriceListId = commercePriceListId;
	}

	public long getOriginalCommercePriceListId() {
		return _originalCommercePriceListId;
	}

	@JSON
	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_columnBitmask = -1L;

		_order = order;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CommercePriceListContractRel.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommercePriceListContractRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommercePriceListContractRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommercePriceListContractRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommercePriceListContractRelImpl commercePriceListContractRelImpl =
			new CommercePriceListContractRelImpl();

		commercePriceListContractRelImpl.setUuid(getUuid());
		commercePriceListContractRelImpl.setCommercePriceListContractRelId(
			getCommercePriceListContractRelId());
		commercePriceListContractRelImpl.setCompanyId(getCompanyId());
		commercePriceListContractRelImpl.setUserId(getUserId());
		commercePriceListContractRelImpl.setUserName(getUserName());
		commercePriceListContractRelImpl.setCreateDate(getCreateDate());
		commercePriceListContractRelImpl.setModifiedDate(getModifiedDate());
		commercePriceListContractRelImpl.setCommerceContractId(
			getCommerceContractId());
		commercePriceListContractRelImpl.setCommercePriceListId(
			getCommercePriceListId());
		commercePriceListContractRelImpl.setOrder(getOrder());
		commercePriceListContractRelImpl.setLastPublishDate(
			getLastPublishDate());

		commercePriceListContractRelImpl.resetOriginalValues();

		return commercePriceListContractRelImpl;
	}

	@Override
	public int compareTo(
		CommercePriceListContractRel commercePriceListContractRel) {

		int value = 0;

		if (getOrder() < commercePriceListContractRel.getOrder()) {
			value = -1;
		}
		else if (getOrder() > commercePriceListContractRel.getOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommercePriceListContractRel)) {
			return false;
		}

		CommercePriceListContractRel commercePriceListContractRel =
			(CommercePriceListContractRel)obj;

		long primaryKey = commercePriceListContractRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommercePriceListContractRelModelImpl
			commercePriceListContractRelModelImpl = this;

		commercePriceListContractRelModelImpl._originalUuid =
			commercePriceListContractRelModelImpl._uuid;

		commercePriceListContractRelModelImpl._originalCompanyId =
			commercePriceListContractRelModelImpl._companyId;

		commercePriceListContractRelModelImpl._setOriginalCompanyId = false;

		commercePriceListContractRelModelImpl._setModifiedDate = false;

		commercePriceListContractRelModelImpl._originalCommerceContractId =
			commercePriceListContractRelModelImpl._commerceContractId;

		commercePriceListContractRelModelImpl._setOriginalCommerceContractId =
			false;

		commercePriceListContractRelModelImpl._originalCommercePriceListId =
			commercePriceListContractRelModelImpl._commercePriceListId;

		commercePriceListContractRelModelImpl._setOriginalCommercePriceListId =
			false;

		commercePriceListContractRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommercePriceListContractRel> toCacheModel() {
		CommercePriceListContractRelCacheModel
			commercePriceListContractRelCacheModel =
				new CommercePriceListContractRelCacheModel();

		commercePriceListContractRelCacheModel.uuid = getUuid();

		String uuid = commercePriceListContractRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commercePriceListContractRelCacheModel.uuid = null;
		}

		commercePriceListContractRelCacheModel.commercePriceListContractRelId =
			getCommercePriceListContractRelId();

		commercePriceListContractRelCacheModel.companyId = getCompanyId();

		commercePriceListContractRelCacheModel.userId = getUserId();

		commercePriceListContractRelCacheModel.userName = getUserName();

		String userName = commercePriceListContractRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commercePriceListContractRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commercePriceListContractRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commercePriceListContractRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commercePriceListContractRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commercePriceListContractRelCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		commercePriceListContractRelCacheModel.commerceContractId =
			getCommerceContractId();

		commercePriceListContractRelCacheModel.commercePriceListId =
			getCommercePriceListId();

		commercePriceListContractRelCacheModel.order = getOrder();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			commercePriceListContractRelCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			commercePriceListContractRelCacheModel.lastPublishDate =
				Long.MIN_VALUE;
		}

		return commercePriceListContractRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommercePriceListContractRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommercePriceListContractRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListContractRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(CommercePriceListContractRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommercePriceListContractRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommercePriceListContractRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListContractRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(CommercePriceListContractRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommercePriceListContractRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _commercePriceListContractRelId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceContractId;
	private long _originalCommerceContractId;
	private boolean _setOriginalCommerceContractId;
	private long _commercePriceListId;
	private long _originalCommercePriceListId;
	private boolean _setOriginalCommercePriceListId;
	private int _order;
	private Date _lastPublishDate;
	private long _columnBitmask;
	private CommercePriceListContractRel _escapedModel;

}