/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.price.list.model.impl;

import com.liferay.commerce.price.list.model.CommercePriceListRel;
import com.liferay.commerce.price.list.model.CommercePriceListRelModel;
import com.liferay.commerce.price.list.model.CommercePriceListRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommercePriceListRel service. Represents a row in the &quot;CommercePriceListRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CommercePriceListRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercePriceListRelImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommercePriceListRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommercePriceListRelModelImpl
	extends BaseModelImpl<CommercePriceListRel>
	implements CommercePriceListRelModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce price list rel model instance should use the <code>CommercePriceListRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommercePriceListRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"commercePriceListRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"commercePriceListId", Types.BIGINT},
		{"order_", Types.INTEGER}, {"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commercePriceListRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercePriceListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommercePriceListRel (uuid_ VARCHAR(75) null,commercePriceListRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,commercePriceListId LONG,order_ INTEGER,lastPublishDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommercePriceListRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commercePriceListRel.order ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommercePriceListRel.order_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.price.list.model.CommercePriceListRel"),
		true);

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long COMMERCEPRICELISTID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ORDER_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommercePriceListRel toModel(
		CommercePriceListRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CommercePriceListRel model = new CommercePriceListRelImpl();

		model.setUuid(soapModel.getUuid());
		model.setCommercePriceListRelId(soapModel.getCommercePriceListRelId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setCommercePriceListId(soapModel.getCommercePriceListId());
		model.setOrder(soapModel.getOrder());
		model.setLastPublishDate(soapModel.getLastPublishDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommercePriceListRel> toModels(
		CommercePriceListRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommercePriceListRel> models = new ArrayList<CommercePriceListRel>(
			soapModels.length);

		for (CommercePriceListRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.price.list.model.CommercePriceListRel"));

	public CommercePriceListRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commercePriceListRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommercePriceListRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commercePriceListRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommercePriceListRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommercePriceListRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommercePriceListRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommercePriceListRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommercePriceListRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommercePriceListRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommercePriceListRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommercePriceListRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommercePriceListRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommercePriceListRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommercePriceListRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommercePriceListRel.class.getClassLoader(),
			CommercePriceListRel.class, ModelWrapper.class);

		try {
			Constructor<CommercePriceListRel> constructor =
				(Constructor<CommercePriceListRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CommercePriceListRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CommercePriceListRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommercePriceListRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommercePriceListRel, Object>>();
		Map<String, BiConsumer<CommercePriceListRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommercePriceListRel, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object uuidObject) {

					commercePriceListRel.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListRelId",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getCommercePriceListRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListRelId",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object commercePriceListRelIdObject) {

					commercePriceListRel.setCommercePriceListRelId(
						(Long)commercePriceListRelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object companyIdObject) {

					commercePriceListRel.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object userIdObject) {

					commercePriceListRel.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object userNameObject) {

					commercePriceListRel.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object createDateObject) {

					commercePriceListRel.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object modifiedDateObject) {

					commercePriceListRel.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getClassNameId();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object classNameIdObject) {

					commercePriceListRel.setClassNameId(
						(Long)classNameIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getClassPK();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object classPKObject) {

					commercePriceListRel.setClassPK((Long)classPKObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListId",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getCommercePriceListId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListId",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object commercePriceListIdObject) {

					commercePriceListRel.setCommercePriceListId(
						(Long)commercePriceListIdObject);
				}

			});
		attributeGetterFunctions.put(
			"order",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getOrder();
				}

			});
		attributeSetterBiConsumers.put(
			"order",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object orderObject) {

					commercePriceListRel.setOrder((Integer)orderObject);
				}

			});
		attributeGetterFunctions.put(
			"lastPublishDate",
			new Function<CommercePriceListRel, Object>() {

				@Override
				public Object apply(CommercePriceListRel commercePriceListRel) {
					return commercePriceListRel.getLastPublishDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			new BiConsumer<CommercePriceListRel, Object>() {

				@Override
				public void accept(
					CommercePriceListRel commercePriceListRel,
					Object lastPublishDateObject) {

					commercePriceListRel.setLastPublishDate(
						(Date)lastPublishDateObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCommercePriceListRelId() {
		return _commercePriceListRelId;
	}

	@Override
	public void setCommercePriceListRelId(long commercePriceListRelId) {
		_commercePriceListRelId = commercePriceListRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@JSON
	@Override
	public long getCommercePriceListId() {
		return _commercePriceListId;
	}

	@Override
	public void setCommercePriceListId(long commercePriceListId) {
		_columnBitmask |= COMMERCEPRICELISTID_COLUMN_BITMASK;

		if (!_setOriginalCommercePriceListId) {
			_setOriginalCommercePriceListId = true;

			_originalCommercePriceListId = _commercePriceListId;
		}

		_commercePriceListId = commercePriceListId;
	}

	public long getOriginalCommercePriceListId() {
		return _originalCommercePriceListId;
	}

	@JSON
	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_columnBitmask = -1L;

		_order = order;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CommercePriceListRel.class.getName()),
			getClassNameId());
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommercePriceListRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommercePriceListRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommercePriceListRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommercePriceListRelImpl commercePriceListRelImpl =
			new CommercePriceListRelImpl();

		commercePriceListRelImpl.setUuid(getUuid());
		commercePriceListRelImpl.setCommercePriceListRelId(
			getCommercePriceListRelId());
		commercePriceListRelImpl.setCompanyId(getCompanyId());
		commercePriceListRelImpl.setUserId(getUserId());
		commercePriceListRelImpl.setUserName(getUserName());
		commercePriceListRelImpl.setCreateDate(getCreateDate());
		commercePriceListRelImpl.setModifiedDate(getModifiedDate());
		commercePriceListRelImpl.setClassNameId(getClassNameId());
		commercePriceListRelImpl.setClassPK(getClassPK());
		commercePriceListRelImpl.setCommercePriceListId(
			getCommercePriceListId());
		commercePriceListRelImpl.setOrder(getOrder());
		commercePriceListRelImpl.setLastPublishDate(getLastPublishDate());

		commercePriceListRelImpl.resetOriginalValues();

		return commercePriceListRelImpl;
	}

	@Override
	public int compareTo(CommercePriceListRel commercePriceListRel) {
		int value = 0;

		if (getOrder() < commercePriceListRel.getOrder()) {
			value = -1;
		}
		else if (getOrder() > commercePriceListRel.getOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommercePriceListRel)) {
			return false;
		}

		CommercePriceListRel commercePriceListRel = (CommercePriceListRel)obj;

		long primaryKey = commercePriceListRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommercePriceListRelModelImpl commercePriceListRelModelImpl = this;

		commercePriceListRelModelImpl._originalUuid =
			commercePriceListRelModelImpl._uuid;

		commercePriceListRelModelImpl._originalCompanyId =
			commercePriceListRelModelImpl._companyId;

		commercePriceListRelModelImpl._setOriginalCompanyId = false;

		commercePriceListRelModelImpl._setModifiedDate = false;

		commercePriceListRelModelImpl._originalClassNameId =
			commercePriceListRelModelImpl._classNameId;

		commercePriceListRelModelImpl._setOriginalClassNameId = false;

		commercePriceListRelModelImpl._originalCommercePriceListId =
			commercePriceListRelModelImpl._commercePriceListId;

		commercePriceListRelModelImpl._setOriginalCommercePriceListId = false;

		commercePriceListRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommercePriceListRel> toCacheModel() {
		CommercePriceListRelCacheModel commercePriceListRelCacheModel =
			new CommercePriceListRelCacheModel();

		commercePriceListRelCacheModel.uuid = getUuid();

		String uuid = commercePriceListRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commercePriceListRelCacheModel.uuid = null;
		}

		commercePriceListRelCacheModel.commercePriceListRelId =
			getCommercePriceListRelId();

		commercePriceListRelCacheModel.companyId = getCompanyId();

		commercePriceListRelCacheModel.userId = getUserId();

		commercePriceListRelCacheModel.userName = getUserName();

		String userName = commercePriceListRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commercePriceListRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commercePriceListRelCacheModel.createDate = createDate.getTime();
		}
		else {
			commercePriceListRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commercePriceListRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commercePriceListRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commercePriceListRelCacheModel.classNameId = getClassNameId();

		commercePriceListRelCacheModel.classPK = getClassPK();

		commercePriceListRelCacheModel.commercePriceListId =
			getCommercePriceListId();

		commercePriceListRelCacheModel.order = getOrder();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			commercePriceListRelCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			commercePriceListRelCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		return commercePriceListRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommercePriceListRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommercePriceListRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CommercePriceListRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommercePriceListRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommercePriceListRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CommercePriceListRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CommercePriceListRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _commercePriceListRelId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _commercePriceListId;
	private long _originalCommercePriceListId;
	private boolean _setOriginalCommercePriceListId;
	private int _order;
	private Date _lastPublishDate;
	private long _columnBitmask;
	private CommercePriceListRel _escapedModel;

}